/* eslint-disable guard-for-in */

import { theme } from '../theme';
import { CountryEnum, Player } from './Players';

/* eslint-disable no-restricted-syntax */
export interface Team {
  id?: string;
  documentId?: string;
  name: string;
  fotMobName?: string;
  shortName?: string;
  logoUrl: string;
  darkModeLogoUrl?: string;
  stadium?: string;
  country?: string;
  countryCode?: string;
  federation?: FederationEnum;
  teamPrimaryColor?: string;
  players?: Player[];
  isPlaceholder?: boolean;
}

export enum FederationEnum {
  EUROPE = 'Europa',
  SOUTH_AMERICA = 'Sydamerika',
  AFRICA = 'Afrika',
  ASIA = 'Asien',
  NORTH_AMERICA = 'Nordamerika',
  OCEANIA = 'Oceanien',
}

export enum LeagueEnum {
  PREMIER_LEAGUE = 'Premier League',
  EFL_CHAMPIONSHIP = 'EFL Championship',
  EFL_LEAGUE_ONE = 'EFL League One',
  EFL_LEAGUE_TWO = 'EFL League Two',
  ALLSVENSKAN = 'Allsvenskan',
  LA_LIGA = 'La Liga',
  SEGUNDA_DIVISION = 'Segunda Division',
  SERIE_A = 'Serie A',
  BUNDESLIGA = 'Bundesliga',
  BUNDESLIGA_2 = '2. Bundesliga',
  LIGUE_1 = 'Ligue 1',
  EREDIVISIE = 'Eredivisie',
  PRIMEIRA_LIGA = 'Primeira Liga',
  TURKISH_SUPER_LIG = 'Süper Lig',
  GREEK_SUPER_LEAGUE = 'Super League 1',
  BELGIAN_PRO_LEAGUE = 'Belgian Pro League',
  SUPERETTAN = 'Superettan',
  ELITESERIEN = 'Eliteserien',
  SUPERLIGA = 'Superliga',
  UKRAINIAN_PREMIER_LEAGUE = 'Ukrainian Premier League',
  SCOTTISH_PREMIERSHIP = 'Scottish Premiership',
  AUSTRIAN_BUNDESLIGA = 'Austrian Bundesliga',
  SWISS_SUPER_LEAGUE = 'Swiss Super League',
  CZECH_FIRST_LEAGUE = 'Czech First League',
  CROATIAN_FIRST_FOOTBALL_LEAGUE = 'Prva HNL',
  SLOVAK_1_LIGA = 'Niké Liga',
  SERBIAN_SUPER_LIGA = 'Serbian SuperLiga',
  AZERBAIJAN_PREMIER_LEAGUE = 'Azerbaijan Premier League',
  NATIONS = 'Landslag',
  PLACEHOLDER = 'Placeholder',
}

export enum TournamentsEnum {
  PREMIER_LEAGUE = 'Premier League',
  FA_CUP = 'FA Cup',
  CARABAO_CUP = 'Carabao Cup',
  CHAMPIONSHIP = 'Championship',
  LA_LIGA = 'La Liga',
  COPA_DEL_REY = 'Copa del Rey',
  SUPERCOPA = 'Supercopa',
  SERIE_A = 'Serie A',
  SUPERCOPPA_ITALIANA = 'Supercoppa Italiana',
  COPPA_ITALIA = 'Coppa Italia',
  BUNDESLIGA = 'Bundesliga',
  BUNDESLIGA_2 = '2. Bundesliga',
  DFB_POKAL = 'DFB-Pokal',
  LIGUE_1 = 'Ligue 1',
  COUPE_DE_FRANCE = 'Coupe de France',
  CHAMPIONS_LEAGUE = 'UEFA Champions League',
  EUROPA_LEAGUE = 'UEFA Europa League',
  CONFERENCE_LEAGUE = 'UEFA Conference League',
  UEFA_SUPER_CUP = 'UEFA Super Cup',
  ALLSVENSKAN = 'Allsvenskan',
  SVENSKA_CUPEN = 'Svenska Cupen',
  SUPERETTAN = 'Superettan',
  ELITESERIEN = 'Eliteserien',
  SUPERLIGA = 'Superligaen',
  EREDIVISIE = 'Eredivisie',
  PRIMEIRA_LIGA = 'Primeira Liga',
  TURKISH_SUPER_LIG = 'Süper Lig',
  BELGIAN_PRO_LEAGUE = 'Belgian Pro League',
  GREEK_SUPER_LEAGUE = 'Super League 1',
  SCOTTISH_PREMIERSHIP = 'Scottish Premiership',
  SWISS_SUPER_LEAGUE = 'Swiss Super League',
  AUSTRIAN_BUNDESLIGA = 'Austrian Bundesliga',
  CZECH_FIRST_LEAGUE = 'Czech First League',
  CROATIAN_FIRST_FOOTBALL_LEAGUE = 'Prva HNL',
  EUROS = 'EM',
  WORLD_CUP = 'VM',
  NATIONS_LEAGUE = 'Nations League',
  EUROS_QUALIFIERS = 'EM-kval',
  WORLD_CUP_QUALIFIERS = 'VM-kval',
  FRIENDLIES = 'Vänskapsmatcher',
  PLACEHOLDER = 'Okänd',
}

export const getTeamByNameAndLeague = (teamName: string, league: string) => Teams[league as LeagueEnum].find((team: Team) => team.name === teamName);

export const getTeamByName = (teamName: string): Team | undefined => {
  for (const league in Teams) {
    const team = Teams[league as LeagueEnum].find((team: Team) => team.name === teamName);
    if (team) return team;
  }
};

export const getTeamsByCountry = (country: string): Team[] => {
  const teams: Team[] = [];
  for (const league in Teams) {
    Teams[league as LeagueEnum].forEach((team: Team) => {
      if (team.country === country) teams.push(team);
    });
  }
  return teams;
};

export const getTeamsObjectByCountry = (): { [key: string]: Team[] } => {
  const teamsByCountry: { [key: string]: Team[] } = {};

  for (const league in Teams) {
    Teams[league as LeagueEnum].forEach((team: Team) => {
      const { country } = team;
      if (!country) return;
      if (!teamsByCountry[country]) {
        teamsByCountry[country] = [] as Team[];
      }
      teamsByCountry[country].push(team);
    });
  }

  // Sort teams alphabetically within each country's array
  Object.keys(teamsByCountry).forEach((country) => {
    teamsByCountry[country].sort((a, b) => a.name.localeCompare(b.name));
  });

  return teamsByCountry;
};

export const getTeamsByTournament = (tournament: string): Team[] => Teams[tournament as LeagueEnum].map((team: Team) => team);

export const getAllTeams = (): Team[] => {
  const teams: Team[] = [];
  for (const league in Teams) {
    Teams[league as LeagueEnum].forEach((team: Team) => {
      if (!team.isPlaceholder) {
        teams.push(team);
      }
    });
  }
  return teams;
};

export const getAllNations = (): Team[] => {
  const nations: Team[] = [];
  for (const league in Teams) {
    if (league === LeagueEnum.NATIONS) {
      Teams[league as LeagueEnum].forEach((team: Team) => {
        nations.push(team);
      });
    }
  }
  return nations;
};

export const getAllNationsObject = (): { [key: string]: Team[] } => {
  const nations: { [key: string]: Team[] } = { Landslag: [] };

  for (const league in Teams) {
    if (league === LeagueEnum.NATIONS) {
      Teams[league as LeagueEnum].forEach((team: Team) => {
        nations.Landslag.push(team);
      });
    }
  }

  const sortedNations = nations.Landslag.sort((a, b) => a.name.localeCompare(b.name));

  return { Landslag: sortedNations };
};

export const getFlagUrlByCountryName = (countryName: string): string => {
  const country = Teams[LeagueEnum.NATIONS].find((team: Team) => team.name === countryName);
  return country?.logoUrl || '';
};

export const getTeamPrimaryColorByName = (teamName: string): string => {
  for (const league in Teams) {
    const team = Teams[league as LeagueEnum].find((team: Team) => team.name === teamName || team.fotMobName === teamName || team.shortName === teamName || teamName.includes(team.name) || team.name.includes(teamName));
    if (team && (team as any).teamPrimaryColor) return (team as any).teamPrimaryColor || theme.colors.black;
  }
  return '';
};

export const getStadiumByHomeTeam = (teamName: string, teamShortName: string, teamId: string): string => {
  const allTeams = getAllTeams();
  const team = allTeams.find((team: Team) => (team.id !== undefined && team.id === teamId) || team.name === teamName || team.shortName === teamShortName || team.fotMobName === teamName || team.fotMobName === teamShortName || team.name === teamShortName || team.shortName === teamName || team.fotMobName === teamName || team.fotMobName === teamShortName || teamName.includes(team.name) || teamShortName.includes(team.name));
  return team?.stadium || teamName || '';
};

export const nationalTeams: Team[] = [
  {
    name: 'England',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/be/Flag_of_England.svg',
    countryCode: 'ENG',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Brasilien',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg',
    countryCode: 'BRA',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Tyskland',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
    countryCode: 'GER',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Belgien',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    countryCode: 'BEL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Nederländerna',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    countryCode: 'NED',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Frankrike',
    logoUrl: 'https://cdn.countryflags.com/thumbs/france/flag-square-500.png',
    countryCode: 'FRA',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Spanien',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg',
    countryCode: 'ESP',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Italien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/italy/flag-square-500.png',
    countryCode: 'ITA',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Argentina',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
    countryCode: 'ARG',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Portugal',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    countryCode: 'POR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Skottland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/scotland/flag-square-500.png',
    countryCode: 'SCO',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Norge',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg',
    countryCode: 'NOR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Danmark',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg',
    countryCode: 'DEN',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Sverige',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg',
    countryCode: 'SWE',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Finland',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg',
    countryCode: 'FIN',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Schweiz',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg',
    countryCode: 'SUI',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Ukraina',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg',
    countryCode: 'UKR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Österrike',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    countryCode: 'AUT',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Polen',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg',
    countryCode: 'POL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Ghana',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg',
    countryCode: 'GHA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Japan',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg',
    countryCode: 'JPN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Tjeckien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/czech-republic/flag-square-500.png',
    countryCode: 'CZE',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Kroatien',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg',
    countryCode: 'CRO',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Slovakien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/slovakia/flag-square-500.png',
    countryCode: 'SVK',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Serbien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/serbia/flag-square-500.png',
    countryCode: 'SRB',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Azerbajdzjan',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg',
    countryCode: 'AZE',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Kosovo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Kosovo.svg',
    countryCode: 'KVX',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Slovenien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/slovenia/flag-square-500.png',
    countryCode: 'SVN',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Montenegro',
    logoUrl: 'https://cdn.countryflags.com/thumbs/montenegro/flag-square-500.png',
    countryCode: 'MNE',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Albanien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/albania/flag-square-500.png',
    countryCode: 'ALB',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Bosnien och Hercegovina',
    logoUrl: 'https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-square-500.png',
    countryCode: 'BIH',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Nordmakedonien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/north-macedonia/flag-square-500.png',
    countryCode: 'MKD',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Bulgarien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/bulgaria/flag-square-500.png',
    countryCode: 'BUL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Uruguay',
    logoUrl: 'https://cdn.countryflags.com/thumbs/uruguay/flag-square-500.png',
    countryCode: 'URU',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Island',
    logoUrl: 'https://cdn.countryflags.com/thumbs/iceland/flag-square-500.png',
    countryCode: 'ISL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Elfenbenskusten',
    logoUrl: 'https://www.countryflags.com/wp-content/uploads/cote-d-ivoire-flag-png-large.png',
    countryCode: 'CIV',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Nigeria',
    logoUrl: 'https://cdn.countryflags.com/thumbs/nigeria/flag-square-500.png',
    countryCode: 'NGA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Surinam',
    logoUrl: 'https://cdn.countryflags.com/thumbs/suriname/flag-square-500.png',
    countryCode: 'SUR',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Gambia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/gambia/flag-square-500.png',
    countryCode: 'GAM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Senegal',
    logoUrl: 'https://cdn.countryflags.com/thumbs/senegal/flag-square-500.png',
    countryCode: 'SEN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Kamerun',
    logoUrl: 'https://cdn.countryflags.com/thumbs/cameroon/flag-square-500.png',
    countryCode: 'CMR',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Marocko',
    logoUrl: 'https://cdn.countryflags.com/thumbs/morocco/flag-square-500.png',
    countryCode: 'MAR',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Tunisien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/tunisia/flag-square-500.png',
    countryCode: 'TUN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Egypten',
    logoUrl: 'https://cdn.countryflags.com/thumbs/egypt/flag-square-500.png',
    countryCode: 'EGY',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Sydafrika',
    logoUrl: 'https://cdn.countryflags.com/thumbs/south-africa/flag-square-500.png',
    countryCode: 'RSA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Algeriet',
    logoUrl: 'https://cdn.countryflags.com/thumbs/algeria/flag-square-500.png',
    countryCode: 'ALG',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Kongo-Kinshasa',
    logoUrl: 'https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-square-500.png',
    countryCode: 'COD',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'El Salvador',
    logoUrl: 'https://cdn.countryflags.com/thumbs/el-salvador/flag-square-500.png',
    countryCode: 'SLV',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Honduras',
    logoUrl: 'https://cdn.countryflags.com/thumbs/honduras/flag-square-500.png',
    countryCode: 'HON',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Costa Rica',
    logoUrl: 'https://cdn.countryflags.com/thumbs/costa-rica/flag-square-500.png',
    countryCode: 'CRC',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Panama',
    logoUrl: 'https://cdn.countryflags.com/thumbs/panama/flag-square-500.png',
    countryCode: 'PAN',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'USA',
    logoUrl: 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-square-500.png',
    countryCode: 'USA',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Mexiko',
    logoUrl: 'https://cdn.countryflags.com/thumbs/mexico/flag-square-500.png',
    countryCode: 'MEX',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Kanada',
    logoUrl: 'https://cdn.countryflags.com/thumbs/canada/flag-square-500.png',
    countryCode: 'CAN',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Jamaica',
    logoUrl: 'https://cdn.countryflags.com/thumbs/jamaica/flag-square-500.png',
    countryCode: 'JAM',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Trinidad och Tobago',
    logoUrl: 'https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-square-500.png',
    countryCode: 'TRI',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Haiti',
    logoUrl: 'https://cdn.countryflags.com/thumbs/haiti/flag-square-500.png',
    countryCode: 'HAI',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Guatemala',
    logoUrl: 'https://cdn.countryflags.com/thumbs/guatemala/flag-square-500.png',
    countryCode: 'GUA',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Nicaragua',
    logoUrl: 'https://cdn.countryflags.com/thumbs/nicaragua/flag-square-500.png',
    countryCode: 'NCA',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Kuba',
    logoUrl: 'https://cdn.countryflags.com/thumbs/cuba/flag-square-500.png',
    countryCode: 'CUB',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Dominikanska republiken',
    logoUrl: 'https://cdn.countryflags.com/thumbs/dominican-republic/flag-square-500.png',
    countryCode: 'DOM',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Honduras',
    logoUrl: 'https://cdn.countryflags.com/thumbs/honduras/flag-square-500.png',
    countryCode: 'HON',
    federation: FederationEnum.NORTH_AMERICA,
  },
  {
    name: 'Sydkorea',
    logoUrl: 'https://cdn.countryflags.com/thumbs/south-korea/flag-square-500.png',
    countryCode: 'KOR',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Kina',
    logoUrl: 'https://cdn.countryflags.com/thumbs/china/flag-square-500.png',
    countryCode: 'CHN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Australien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/australia/flag-square-500.png',
    countryCode: 'AUS',
    federation: FederationEnum.OCEANIA,
  },
  {
    name: 'Nya Zeeland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/new-zealand/flag-square-500.png',
    countryCode: 'NZL',
    federation: FederationEnum.OCEANIA,
  },
  {
    name: 'Färöarna',
    logoUrl: 'https://cdn.countryflags.com/thumbs/faroe-islands/flag-square-500.png',
    countryCode: 'FRO',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Turkiet',
    logoUrl: 'https://cdn.countryflags.com/thumbs/turkey/flag-square-500.png',
    countryCode: 'TUR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Rumänien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/romania/flag-square-500.png',
    countryCode: 'ROU',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Ungern',
    logoUrl: 'https://cdn.countryflags.com/thumbs/hungary/flag-square-500.png',
    countryCode: 'HUN',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Grekland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/greece/flag-square-500.png',
    countryCode: 'GRE',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Kazakstan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/kazakhstan/flag-square-500.png',
    countryCode: 'KAZ',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Kuwait',
    logoUrl: 'https://cdn.countryflags.com/thumbs/kuwait/flag-square-500.png',
    countryCode: 'KUW',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Libanon',
    logoUrl: 'https://cdn.countryflags.com/thumbs/lebanon/flag-square-500.png',
    countryCode: 'LBN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Jordanien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/jordan/flag-square-500.png',
    countryCode: 'JOR',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Armenien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/armenia/flag-square-500.png',
    countryCode: 'ARM',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Georgien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/georgia/flag-square-500.png',
    countryCode: 'GEO',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Iran',
    logoUrl: 'https://cdn.countryflags.com/thumbs/iran/flag-square-500.png',
    countryCode: 'IRN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Irak',
    logoUrl: 'https://cdn.countryflags.com/thumbs/iraq/flag-square-500.png',
    countryCode: 'IRQ',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Kenya',
    logoUrl: 'https://cdn.countryflags.com/thumbs/kenya/flag-square-500.png',
    countryCode: 'KEN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Uganda',
    logoUrl: 'https://cdn.countryflags.com/thumbs/uganda/flag-square-500.png',
    countryCode: 'UGA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Zimbabwe',
    logoUrl: 'https://cdn.countryflags.com/thumbs/zimbabwe/flag-square-500.png',
    countryCode: 'ZIM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Zambia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/zambia/flag-square-500.png',
    countryCode: 'ZAM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Tanzania',
    logoUrl: 'https://cdn.countryflags.com/thumbs/tanzania/flag-square-500.png',
    countryCode: 'TAN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Syrien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/syria/flag-square-500.png',
    countryCode: 'SYR',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Israel',
    logoUrl: 'https://cdn.countryflags.com/thumbs/israel/flag-square-500.png',
    countryCode: 'ISR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Cypern',
    logoUrl: 'https://cdn.countryflags.com/thumbs/cyprus/flag-square-500.png',
    countryCode: 'CYP',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Irland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/ireland/flag-square-500.png',
    countryCode: 'IRL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Wales',
    logoUrl: 'https://cdn.countryflags.com/thumbs/wales/flag-square-500.png',
    countryCode: 'WAL',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Nordirland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/northern-ireland/flag-square-500.png',
    countryCode: 'NIR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Estland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/estonia/flag-square-500.png',
    countryCode: 'EST',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Lettland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/latvia/flag-square-500.png',
    countryCode: 'LAT',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Litauen',
    logoUrl: 'https://cdn.countryflags.com/thumbs/lithuania/flag-square-500.png',
    countryCode: 'LTU',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Moldavien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/moldova/flag-square-500.png',
    countryCode: 'MDA',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Luxemburg',
    logoUrl: 'https://cdn.countryflags.com/thumbs/luxembourg/flag-square-500.png',
    countryCode: 'LUX',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Malta',
    logoUrl: 'https://cdn.countryflags.com/thumbs/malta/flag-square-500.png',
    countryCode: 'MLT',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Andorra',
    logoUrl: 'https://cdn.countryflags.com/thumbs/andorra/flag-square-500.png',
    countryCode: 'AND',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Paraguay',
    logoUrl: 'https://cdn.countryflags.com/thumbs/paraguay/flag-square-500.png',
    countryCode: 'PAR',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Peru',
    logoUrl: 'https://cdn.countryflags.com/thumbs/peru/flag-square-500.png',
    countryCode: 'PER',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Chile',
    logoUrl: 'https://cdn.countryflags.com/thumbs/chile/flag-square-500.png',
    countryCode: 'CHI',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Ecuador',
    logoUrl: 'https://cdn.countryflags.com/thumbs/ecuador/flag-square-500.png',
    countryCode: 'ECU',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Bolivia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/bolivia/flag-square-500.png',
    countryCode: 'BOL',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Venezuela',
    logoUrl: 'https://cdn.countryflags.com/thumbs/venezuela/flag-square-500.png',
    countryCode: 'VEN',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Colombia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/colombia/flag-square-500.png',
    countryCode: 'COL',
    federation: FederationEnum.SOUTH_AMERICA,
  },
  {
    name: 'Brunei',
    logoUrl: 'https://cdn.countryflags.com/thumbs/brunei/flag-square-500.png',
    countryCode: 'BRU',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Filippinerna',
    logoUrl: 'https://cdn.countryflags.com/thumbs/philippines/flag-square-500.png',
    countryCode: 'PHI',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Thailand',
    logoUrl: 'https://cdn.countryflags.com/thumbs/thailand/flag-square-500.png',
    countryCode: 'THA',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Vietnam',
    logoUrl: 'https://cdn.countryflags.com/thumbs/vietnam/flag-square-500.png',
    countryCode: 'VIE',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Malaysia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/malaysia/flag-square-500.png',
    countryCode: 'MAS',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Singapore',
    logoUrl: 'https://cdn.countryflags.com/thumbs/singapore/flag-square-500.png',
    countryCode: 'SIN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Indonesien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/indonesia/flag-square-500.png',
    countryCode: 'IDN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Kambodja',
    logoUrl: 'https://cdn.countryflags.com/thumbs/cambodia/flag-square-500.png',
    countryCode: 'CAM',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Laos',
    logoUrl: 'https://cdn.countryflags.com/thumbs/laos/flag-square-500.png',
    countryCode: 'LAO',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Myanmar',
    logoUrl: 'https://cdn.countryflags.com/thumbs/myanmar/flag-square-500.png',
    countryCode: 'MYA',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Libyen',
    logoUrl: 'https://cdn.countryflags.com/thumbs/libya/flag-square-500.png',
    countryCode: 'LBY',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Sudan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/sudan/flag-square-500.png',
    countryCode: 'SUD',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Etiopien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/ethiopia/flag-square-500.png',
    countryCode: 'ETH',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Somalia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/somalia/flag-square-500.png',
    countryCode: 'SOM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Eritrea',
    logoUrl: 'https://cdn.countryflags.com/thumbs/eritrea/flag-square-500.png',
    countryCode: 'ERI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Djibouti',
    logoUrl: 'https://cdn.countryflags.com/thumbs/djibouti/flag-square-500.png',
    countryCode: 'DJI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Mauretanien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/mauritania/flag-square-500.png',
    countryCode: 'MTN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Mali',
    logoUrl: 'https://cdn.countryflags.com/thumbs/mali/flag-square-500.png',
    countryCode: 'MLI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Burkina Faso',
    logoUrl: 'https://cdn.countryflags.com/thumbs/burkina-faso/flag-square-500.png',
    countryCode: 'BFA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Niger',
    logoUrl: 'https://cdn.countryflags.com/thumbs/niger/flag-square-500.png',
    countryCode: 'NIG',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Tchad',
    logoUrl: 'https://cdn.countryflags.com/thumbs/chad/flag-square-500.png',
    countryCode: 'CHA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Centralafrikanska republiken',
    logoUrl: 'https://cdn.countryflags.com/thumbs/central-african-republic/flag-square-500.png',
    countryCode: 'CAF',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Gabon',
    logoUrl: 'https://cdn.countryflags.com/thumbs/gabon/flag-square-500.png',
    countryCode: 'GAB',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Kongo-Brazzaville',
    logoUrl: 'https://cdn.countryflags.com/thumbs/congo-republic-of-the/flag-square-500.png',
    countryCode: 'CGO',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Angola',
    logoUrl: 'https://cdn.countryflags.com/thumbs/angola/flag-square-500.png',
    countryCode: 'ANG',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Togo',
    logoUrl: 'https://cdn.countryflags.com/thumbs/togo/flag-square-500.png',
    countryCode: 'TOG',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Benin',
    logoUrl: 'https://cdn.countryflags.com/thumbs/benin/flag-square-500.png',
    countryCode: 'BEN',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Burundi',
    logoUrl: 'https://cdn.countryflags.com/thumbs/burundi/flag-square-500.png',
    countryCode: 'BDI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Rwanda',
    logoUrl: 'https://cdn.countryflags.com/thumbs/rwanda/flag-square-500.png',
    countryCode: 'RWA',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Namibia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/namibia/flag-square-500.png',
    countryCode: 'NAM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Botswana',
    logoUrl: 'https://cdn.countryflags.com/thumbs/botswana/flag-square-500.png',
    countryCode: 'BOT',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Swaziland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/swaziland/flag-square-500.png',
    countryCode: 'SWZ',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Lesotho',
    logoUrl: 'https://cdn.countryflags.com/thumbs/lesotho/flag-square-500.png',
    countryCode: 'LES',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Sierra Leone',
    logoUrl: 'https://cdn.countryflags.com/thumbs/sierra-leone/flag-square-500.png',
    countryCode: 'SLE',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Liberia',
    logoUrl: 'https://cdn.countryflags.com/thumbs/liberia/flag-square-500.png',
    countryCode: 'LBR',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Guinea',
    logoUrl: 'https://cdn.countryflags.com/thumbs/guinea/flag-square-500.png',
    countryCode: 'GUI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Guinea-Bissau',
    logoUrl: 'https://cdn.countryflags.com/thumbs/guinea-bissau/flag-square-500.png',
    countryCode: 'GNB',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Kap Verde',
    logoUrl: 'https://cdn.countryflags.com/thumbs/cape-verde/flag-square-500.png',
    countryCode: 'CPV',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'São Tomé och Príncipe',
    logoUrl: 'https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-square-500.png',
    countryCode: 'STP',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Komorerna',
    logoUrl: 'https://cdn.countryflags.com/thumbs/comoros/flag-square-500.png',
    countryCode: 'COM',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Ryssland',
    logoUrl: 'https://cdn.countryflags.com/thumbs/russia/flag-square-500.png',
    countryCode: 'RUS',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Belarus',
    logoUrl: 'https://cdn.countryflags.com/thumbs/belarus/flag-square-500.png',
    countryCode: 'BLR',
    federation: FederationEnum.EUROPE,
  },
  {
    name: 'Malawi',
    logoUrl: 'https://cdn.countryflags.com/thumbs/malawi/flag-square-500.png',
    countryCode: 'MWI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Mozambique',
    logoUrl: 'https://cdn.countryflags.com/thumbs/mozambique/flag-square-500.png',
    countryCode: 'MOZ',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Madagaskar',
    logoUrl: 'https://cdn.countryflags.com/thumbs/madagascar/flag-square-500.png',
    countryCode: 'MAD',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Mauritius',
    logoUrl: 'https://cdn.countryflags.com/thumbs/mauritius/flag-square-500.png',
    countryCode: 'MRI',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Seychellerna',
    logoUrl: 'https://cdn.countryflags.com/thumbs/seychelles/flag-square-500.png',
    countryCode: 'SEY',
    federation: FederationEnum.AFRICA,
  },
  {
    name: 'Indien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/india/flag-square-500.png',
    countryCode: 'IND',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Pakistan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/pakistan/flag-square-500.png',
    countryCode: 'PAK',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Bangladesh',
    logoUrl: 'https://cdn.countryflags.com/thumbs/bangladesh/flag-square-500.png',
    countryCode: 'BAN',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Sri Lanka',
    logoUrl: 'https://cdn.countryflags.com/thumbs/sri-lanka/flag-square-500.png',
    countryCode: 'SRI',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Nepal',
    logoUrl: 'https://cdn.countryflags.com/thumbs/nepal/flag-square-500.png',
    countryCode: 'NEP',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Bhutan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/bhutan/flag-square-500.png',
    countryCode: 'BHU',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Maldiverna',
    logoUrl: 'https://cdn.countryflags.com/thumbs/maldives/flag-square-500.png',
    countryCode: 'MDV',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Nordkorea',
    logoUrl: 'https://cdn.countryflags.com/thumbs/north-korea/flag-square-500.png',
    countryCode: 'PRK',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Turkmenistan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/turkmenistan/flag-square-500.png',
    countryCode: 'TKM',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Uzbekistan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/uzbekistan/flag-square-500.png',
    countryCode: 'UZB',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Tadzjikistan',
    logoUrl: 'https://cdn.countryflags.com/thumbs/tajikistan/flag-square-500.png',
    countryCode: 'TJK',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Saudiarabien',
    logoUrl: 'https://cdn.countryflags.com/thumbs/saudi-arabia/flag-square-500.png',
    countryCode: 'KSA',
    federation: FederationEnum.ASIA,
  },
  {
    name: 'Placeholder',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Flag_of_None_%28square%29.svg',
    countryCode: 'NONE',
  },
];

type TeamsType = { [key: string]: Team[] };

export const Teams: TeamsType = {
  [LeagueEnum.PREMIER_LEAGUE]: [
    {
      name: 'Arsenal',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
      stadium: 'Emirates Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#E40514',
      id: '9825',
    },
    {
      name: 'Chelsea',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
      stadium: 'Stamford Bridge',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#034694',
      id: '8455',
    },
    {
      name: 'Liverpool',
      logoUrl: 'https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2022-07/MicrosoftTeams-image%20%2818%29%20%281%29.webp?itok=mhoZb73-&width=1680',
      // darkModeLogoUrl: 'https://mahonpointsc.ie/wp-content/uploads/2021/09/Liverpool-Logo-Final-1.png',
      stadium: 'Anfield',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#d11f2b',
      id: '8650',
    },
    {
      name: 'Manchester City',
      shortName: 'Man City',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
      stadium: 'Etihad Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#6CABDD',
      id: '8456',
    },
    {
      name: 'Manchester United',
      shortName: 'Man United',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
      stadium: 'Old Trafford',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#DA291C',
      id: '10260',
    },
    {
      name: 'Tottenham',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8586.png',
      stadium: 'Tottenham Hotspur Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#132257',
      id: '8586',
    },
    {
      name: 'Everton',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',
      stadium: 'Goodison Park',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#003399',
    },
    {
      name: 'Leicester',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2d/Leicester_City_crest.svg',
      stadium: 'King Power Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#003090',
    },
    {
      name: 'West Ham',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg',
      stadium: 'London Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#7A263A',
    },
    {
      name: 'Aston Villa',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/1280px-Aston_Villa_FC_new_crest.svg.png',
      stadium: 'Villa Park',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#7A003C',
      id: '10252',
    },
    {
      name: 'Wolves',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg',
      stadium: 'Molineux Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#FDB913',
    },
    {
      name: 'Southampton',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c9/FC_Southampton.svg',
      stadium: 'St. Mary\'s Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#D71920',
    },
    {
      name: 'Newcastle',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
      stadium: 'St. James\' Park',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#000000',
      id: '10261',
    },
    {
      name: 'Crystal Palace',
      shortName: 'C. Palace',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg',
      stadium: 'Selhurst Park',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#1B458F',
    },
    {
      name: 'Brighton',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg',
      stadium: 'AMEX Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#0057B8',
    },
    {
      name: 'Ipswich',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg',
      stadium: 'Portman Road',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#0000FF',
    },
    {
      name: 'Nottingham Forest',
      shortName: 'N. Forest',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg',
      stadium: 'City Ground',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#FF0000',
    },
    {
      name: 'Brentford',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg',
      stadium: 'Brentford Community Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#E30613',
    },
    {
      name: 'Bournemouth',
      shortName: 'B‘mouth',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg',
      stadium: 'Vitality Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#DA291C',
    },
    {
      name: 'Fulham',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg',
      stadium: 'Craven Cottage',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#000000',
    },
  ],
  [LeagueEnum.EFL_CHAMPIONSHIP]: [
    {
      name: 'Preston North End',
      shortName: 'Preston',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/82/Preston_North_End_FC.svg',
      stadium: 'Deepdale',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#FFFFFF',
    },
    {
      name: 'Plymouth Argyle',
      shortName: 'Plymouth',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a8/Plymouth_Argyle_F.C._logo.svg',
      stadium: 'Home Park',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#004f3e',
    },
  ],
  [LeagueEnum.EFL_LEAGUE_ONE]: [
    {
      name: 'Bolton Wanderers',
      shortName: 'Bolton',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/82/Bolton_Wanderers_FC_logo.svg',
      stadium: 'University of Bolton Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#21397F',
    },
  ],
  [LeagueEnum.EFL_LEAGUE_TWO]: [
    {
      name: 'Walsall',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ef/Walsall_FC.svg',
      stadium: 'Bescot Stadium',
      country: CountryEnum.ENGLAND,
      teamPrimaryColor: '#FF0000',
    },
  ],
  [LeagueEnum.ALLSVENSKAN]: [
    {
      name: 'Djurgården',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Djurgardens_IF_logo.svg',
      stadium: 'Tele2 Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#1261ae',
      id: '9802',
    },
    {
      name: 'Hammarby IF',
      shortName: 'Hammarby',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Hammarby_IF_logo.svg/1920px-Hammarby_IF_logo.svg.png',
      stadium: 'Tele2 Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#008000',
      id: '8248',
    },
    {
      name: 'Malmö FF',
      shortName: 'Malmö',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Malmo_FF_logo.svg',
      stadium: 'Eleda Stadion',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#2b98db',
      id: '10237',
    },
    {
      name: 'IFK Göteborg',
      logoUrl: 'https://ifkgoteborg.se/wp-content/uploads/2017/09/IFK-logo.png',
      stadium: 'Gamla Ullevi',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#2b519c',
      id: '9893',
    },
    {
      name: 'AIK',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8349.png',
      stadium: 'Strawberry Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#023154',
      id: '8349',
    },
    {
      name: 'IFK Norrköping',
      shortName: 'Norrköping',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/IFK_Norrkoping_logo.svg',
      stadium: 'PlatinumCars Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#0052a0',
      id: '8449',
    },
    {
      name: 'BK Häcken',
      shortName: 'Häcken',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5d/BK_Hacken_logo.svg',
      stadium: 'Bravida Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#ffdf28',
      id: '8428',
    },
    {
      name: 'IFK Värnamo',
      shortName: 'Värnamo',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/IFK_Varnamo_logo.svg',
      stadium: 'Finnvedsvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#006ab3',
      id: '6181',
    },
    {
      name: 'Degerfors',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/90/Degerfors_IF_logo.svg',
      stadium: 'Stora Valla',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#f80c04',
      id: '6544',
    },
    {
      name: 'Elfsborg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/37/IF_Elfsborg_logo.svg',
      stadium: 'Borås Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#f8d204',
      id: '8014',
    },
    {
      name: 'GAIS',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a3/GAIS_logo.svg',
      stadium: 'Gamla Ullevi',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '##398d50',
      id: '8297',
    },
    {
      name: 'Östers IF',
      shortName: 'Öster',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Osters_IF_logo.svg',
      stadium: 'Myresjöhus Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#dc362e',
      id: '8641',
    },
    {
      name: 'Mjällby',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Mjallby_AIF_logo.svg',
      stadium: 'Strandvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#fed304',
      id: '8127',
    },
    {
      name: 'Halmstad BK',
      shortName: 'Halmstad',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/66/Halmstad_BK_logo.svg',
      stadium: 'Örjans Vall',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#0258a3',
      id: '8310',
    },
    {
      name: 'IK Sirius',
      shortName: 'Sirius',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cf/IK_Sirius_logo.svg',
      stadium: 'Studenternas IP',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#145caf',
      id: '6694',
    },
    {
      name: 'Brommapojkarna',
      shortName: 'BP',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/20/IF_Brommapojkarna_logo.svg',
      stadium: 'Grimsta IP',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#df1e1f',
      id: '8501',
    },
  ],
  [LeagueEnum.LA_LIGA]: [
    {
      name: 'Real Madrid',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
      stadium: 'Santiago Bernabéu',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#fbbe00',
      id: '8633',
    },
    {
      name: 'FC Barcelona',
      shortName: 'Barcelona',
      fotMobName: 'Barcelona',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
      // stadium: 'Camp Nou',
      stadium: 'Estadi Olímpic Lluís Companys',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#a50044',
      id: '8634',
    },
    {
      name: 'Atletico Madrid',
      shortName: 'Atl. Madrid',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Atletico_Madrid_Logo_2024.svg',
      stadium: 'Wanda Metropolitano',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#cb3524',
      id: '9906',
    },
    {
      name: 'Sevilla',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg',
      stadium: 'Ramón Sánchez Pizjuán',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#d8091d',
    },
    {
      name: 'Valencia',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg',
      stadium: 'Mestalla',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#ee7836',
      id: '10267',
    },
    {
      name: 'Real Sociedad',
      shortName: 'R. Sociedad',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg',
      stadium: 'Estadio Anoeta',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Villarreal',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Villarreal_CF_logo-en.svg',
      stadium: 'Estadio de la Cerámica',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#fee766',
    },
    {
      name: 'Real Betis',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg',
      stadium: 'Estadio Benito Villamarín',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#00964a',
    },
    {
      name: 'Athletic Bilbao',
      shortName: 'Ath. Bilbao',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg',
      stadium: 'Estadio San Mamés',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#ee211e',
      id: '8315',
    },
    {
      name: 'Girona FC',
      shortName: 'Girona',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f7/Girona_FC_Logo.svg',
      stadium: 'Estadi Montilivi',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#d50000',
    },
    {
      name: 'RCD Espanyol',
      shortName: 'Espanyol',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/RCD_Espanyol_crest.svg',
      stadium: 'Stage Front Stadium',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Real Valladolid',
      shortName: 'Valladolid',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Real_Valladolid_Logo.svg',
      stadium: 'Estadio José Zorrilla',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#921591',
    },
    {
      name: 'Getafe',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/46/Getafe_logo.svg',
      stadium: 'Coliseum Alfonso Pérez',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#057cbc',
    },
    {
      name: 'Celta Vigo',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/RC_Celta_de_Vigo_logo.svg',
      stadium: 'Estadio de Balaídos',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#8ac4ee',
    },
    {
      name: 'Deportivo Alavés',
      fotMobName: 'Deportivo Alaves',
      shortName: 'Alavés',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f8/Deportivo_Alaves_logo_%282020%29.svg',
      stadium: 'Estadio de Mendizorroza',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#012ea1',
    },
    {
      name: 'U.D Las Palmas',
      shortName: 'Las Palmas',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/20/UD_Las_Palmas_logo.svg',
      stadium: 'Estadio de Gran Canaria',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#fcdb14',
    },
    {
      name: 'Osasuna',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/38/CA_Osasuna_2024_crest.svg',
      stadium: 'Estadio El Sadar',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#d80723',
    },
    {
      name: 'Leganés',
      fotMobName: 'Leganes',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b8/Club_Deportivo_Legan%C3%A9s_logo.svg',
      stadium: 'Estadio Municipal de Butarque',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#03196f',
    },
    {
      name: 'Rayo Vallecano',
      shortName: 'Rayo',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d8/Rayo_Vallecano_logo.svg',
      stadium: 'Estadio de Vallecas',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#e53115',
    },
    {
      name: 'RCD Mallorca',
      shortName: 'Mallorca',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Rcd_mallorca.svg',
      stadium: 'Estadio Mallorca Son Moix',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#ee1620',
    },
  ],
  [LeagueEnum.SEGUNDA_DIVISION]: [
    {
      name: 'Deportivo La Coruña',
      shortName: 'Deportivo',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/RC_Deportivo_La_Coru%C3%B1a_logo.svg',
      stadium: 'Riazor',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#56105d',
    },
    {
      name: 'Sporting Gijón',
      shortName: 'R. Sporting',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/48/Real_Sporting_de_Gijon.svg',
      stadium: 'El Molinón',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#e10012',
    },
    {
      name: 'Málaga CF',
      shortName: 'Málaga',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6d/M%C3%A1laga_CF.svg',
      stadium: 'La Rosaleda',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Real Oviedo',
      shortName: 'Real Oviedo',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Real_Oviedo_logo.svg',
      stadium: 'Carlos Tartiere',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#054aa2',
    },
    {
      name: 'Racing Santander',
      shortName: 'R. Santander',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f5/Racing_de_Santander_logo.svg',
      stadium: 'El Sardinero',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#2c9a29',
    },
    {
      name: 'CD Tenerife',
      shortName: 'Tenerife',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f9/CD_Tenerife_logo.svg',
      stadium: 'Heliodoro Rodríguez López',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#0e339d',
    },
    {
      name: 'Real Zaragoza',
      shortName: 'Zaragoza',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/69/Real_Zaragoza_logo.svg',
      stadium: 'La Romareda',
      country: CountryEnum.SPAIN,
      teamPrimaryColor: '#fe000a',
    },
  ],
  [LeagueEnum.SERIE_A]: [
    {
      name: 'Juventus',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9885.png',
      stadium: 'Allianz Stadium',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#000000',
      id: '9885',
    },
    {
      name: 'Inter',
      fotMobName: 'Internazionale',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',
      stadium: 'Giuseppe Meazza',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#01229c',
      id: '8636',
    },
    {
      name: 'AC Milan',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
      stadium: 'San Siro',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#e3032a',
      id: '8564',
    },
    {
      name: 'AS Roma',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
      stadium: 'Stadio Olimpico',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#8f1e2c',
      id: '8686',
    },
    {
      name: 'Napoli',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9875.png',
      stadium: 'Stadio Diego Armando Maradona',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#02a1db',
      id: '9875',
    },
    {
      name: 'Lazio',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg',
      stadium: 'Stadio Olimpico',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#87d9f8',
    },
    {
      name: 'Fiorentina',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg',
      stadium: 'Stadio Artemio Franchi',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#61318c',
      id: '8535',
    },
    {
      name: 'Atalanta',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/66/AtalantaBC.svg',
      stadium: 'Gewiss Stadium',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#275baf',
      id: '8524',
    },
    {
      name: 'Bologna',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bologna_F.C._1909_logo.svg',
      stadium: 'Stadio Renato Dall\'Ara',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#a0182e',
    },
    {
      name: 'Genoa',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Genoa_CFC_crest.svg',
      stadium: 'Stadio Luigi Ferraris',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#00213c',
    },
    {
      name: 'Udinese',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/ce/Udinese_Calcio_logo.svg',
      stadium: 'Dacia Arena',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'Parma',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Logo_Parma_Calcio_1913_%28adozione_2016%29.svg',
      stadium: 'Stadio Ennio Tardini',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#f1c516',
    },
    {
      name: 'Torino',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_Logo.svg',
      stadium: 'Stadio Olimpico Grande Torino',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#8a1912',
    },
    {
      name: 'Empoli',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Empoli_FC.png',
      stadium: 'Stadio Carlo Castellani',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#005ea7',
    },
    {
      name: 'Monza',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a7/AC_Monza_logo_%282021%29.svg',
      stadium: 'Stadio Brianteo',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#ee0e35',
    },
    {
      name: 'Hellas Verona',
      shortName: 'H. Verona',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/Hellas_Verona_FC_logo_%282020%29.svg',
      stadium: 'Stadio Marcantonio Bentegodi',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#ffd100',
    },
    {
      name: 'Cagliari',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/61/Cagliari_Calcio_1920.svg',
      stadium: 'Unipol Domus',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#011d40',
    },
    {
      name: 'Venezia',
      logoUrl: 'https://shop.veneziafc.it/cdn/shop/files/logo_veneziafc.svg?v=1720436518&width=120',
      stadium: 'Stadio Pierluigi Penzo',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#fd7f18',
    },
    {
      name: 'Lecce',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9888.png',
      stadium: 'Stadio Via del Mare',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#012857',
    },
    {
      name: 'Como',
      shortName: 'Como',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Logo_Como_1907_-_2019.svg',
      stadium: 'Stadio Giuseppe Sinigaglia',
      country: CountryEnum.ITALY,
      teamPrimaryColor: '#083f69',
    },
  ],
  [LeagueEnum.BUNDESLIGA]: [
    {
      name: 'Bayern München',
      shortName: 'FC Bayern',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg',
      stadium: 'Allianz Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#ed0038',
      id: '9823',
    },
    {
      name: 'Borussia Dortmund',
      shortName: 'Dortmund',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
      stadium: 'Signal Iduna Park',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#ffd900',
      id: '9789',
    },
    {
      name: 'RB Leipzig',
      shortName: 'Leipzig',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',
      stadium: 'Red Bull Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#d50000',
    },
    {
      name: 'Bayer Leverkusen',
      shortName: 'Leverkusen',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg',
      stadium: 'BayArena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#d50000',
      id: '8178',
    },
    {
      name: 'Eintracht Frankfurt',
      shortName: 'Frankfurt',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9810.png',
      stadium: 'Deutsche Bank Park',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#e0000c',
    },
    {
      name: 'VfB Stuttgart',
      shortName: 'Stuttgart',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg',
      stadium: 'Mercedes-Benz Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#fddd02',
    },
    {
      name: 'Mönchengladbach',
      shortName: 'Gladbach',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg',
      stadium: 'Borussia-Park',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#1a191a',
    },
    {
      name: 'VfL Bochum',
      shortName: 'Bochum',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/72/VfL_Bochum_logo.svg',
      stadium: 'Vonovia Ruhrstadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#005ba5',
    },
    {
      name: 'Hoffenheim',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg',
      stadium: 'PreZero Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#1060b6',
    },
    {
      name: 'Holstein Kiel',
      shortName: 'Kiel',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Holstein_Kiel_Logo.svg',
      stadium: 'Holstein-Stadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#04569d',
    },
    {
      name: 'Mainz 05',
      shortName: 'Mainz',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Logo_Mainz_05.svg',
      stadium: 'Opel Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#e6001f',
    },
    {
      name: 'Union Berlin',
      shortName: 'U. Berlin',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/44/1._FC_Union_Berlin_Logo.svg',
      stadium: 'Stadion An der Alten Försterei',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#ec121d',
    },
    {
      name: 'Freiburg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6d/SC_Freiburg_logo.svg',
      stadium: 'Schwarzwald-Stadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'Augsburg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/FC_Augsburg_logo.svg',
      stadium: 'WWK Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#ed1c24',
    },
    {
      name: 'Werder Bremen',
      shortName: 'W. Bremen',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg',
      stadium: 'Weserstadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#179151',
    },
    {
      name: 'VfL Wolfsburg',
      shortName: 'Wolfsburg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/VfL_Wolfsburg_Logo.svg',
      stadium: 'Volkswagen Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#50a803',
    },
    {
      name: 'St. Pauli',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8f/FC_St._Pauli_logo_%282018%29.svg',
      stadium: 'Millerntor-Stadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#624737',
    },
    {
      name: 'Heidenheim',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/1._FC_Heidenheim_1846.svg',
      stadium: 'Voith-Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#e10012',
    },
  ],
  [LeagueEnum.BUNDESLIGA_2]: [
    {
      name: 'Hamburger SV',
      shortName: 'Hamburg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Hamburger_SV_logo.svg',
      stadium: 'Volksparkstadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#195bb4',
      id: '9790',
    },
    {
      name: 'Schalke 04',
      shortName: 'Schalke',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/FC_Schalke_04_Logo.svg',
      stadium: 'Veltins-Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#01499d',
    },
    {
      name: '1. FC Köln',
      shortName: 'Köln',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/01/1._FC_Koeln_Logo_2014%E2%80%93.svg',
      stadium: 'RheinEnergieStadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#d7000d',
    },
    {
      name: 'Düsseldorf',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Fortuna_D%C3%BCsseldorf.png',
      stadium: 'Merkur Spiel-Arena',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#f80000',
    },
    {
      name: 'Hertha Berlin',
      shortName: 'Hertha BSC',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Hertha_BSC_Logo_2012.svg',
      stadium: 'Olympiastadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#004892',
    },
    {
      name: 'Hannover 96',
      shortName: 'Hannover',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Hannover_96_Logo.svg',
      stadium: 'Niedersachsenstadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#069e2e',
    },
    {
      name: '1. FC Nürnberg',
      shortName: 'Nürnberg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/1._FC_N%C3%BCrnberg_logo.svg',
      stadium: 'Max-Morlock-Stadion',
      country: CountryEnum.GERMANY,
      teamPrimaryColor: '#ab081e',
    },
  ],
  [LeagueEnum.LIGUE_1]: [
    {
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
      stadium: 'Parc des Princes',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#004170',
      id: '9847',
    },
    {
      name: 'Lyon',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Olympique_Lyonnais_logo.svg',
      stadium: 'Groupama Stadium',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#0b3d91',
    },
    {
      name: 'Marseille',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',
      stadium: 'Stade Vélodrome',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#0597d9',
    },
    {
      name: 'AS Monaco',
      shortName: 'Monaco',
      fotMobName: 'Monaco',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cf/LogoASMonacoFC2021.svg',
      stadium: 'Stade Louis II',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#e30613',
    },
    {
      name: 'Stade Brestois',
      shortName: 'Brest',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/05/Stade_Brestois_29_logo.svg',
      stadium: 'Stade Francis-Le Blé',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#e30613',
    },
    {
      name: 'LOSC Lille',
      shortName: 'Lille',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg',
      stadium: 'Stade Pierre-Mauroy',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#e1170e',
    },
    {
      name: 'Stade Rennais',
      shortName: 'Rennes',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg',
      stadium: 'Roazhon Park',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'OGC Nice',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg',
      stadium: 'Allianz Riviera',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#ee1620',
    },
    {
      name: 'Montpellier',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a8/Montpellier_HSC_logo.svg',
      stadium: 'Stade de la Mosson',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#d97042',
    },
    {
      name: 'Angers SCO',
      shortName: 'Angers',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Angers_SCO_logo.svg',
      stadium: 'Stade Raymond Kopa',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#c7a77c',
    },
    {
      name: 'AJ Auxerre',
      shortName: 'Auxerre',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/51/AJAuxerreLogo.svg',
      stadium: 'Stade de l\'Abbé-Deschamps',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#0b3d91',
    },
    {
      name: 'Le Havre',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Le_Havre_AC_logo.svg',
      stadium: 'Stade Océane',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#79bde8',
    },
    {
      name: 'RC Lens',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg',
      stadium: 'Stade Bollaert-Delelis',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#fcd116',
    },
    {
      name: 'Nantes',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Logo_FC_Nantes_%28avec_fond%29_-_2019.svg',
      stadium: 'Stade de la Beaujoire',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#fddd02',
    },
    {
      name: 'Stade de Reims',
      shortName: 'Stade Reims',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/19/Stade_de_Reims_logo.svg',
      stadium: 'Stade Auguste-Delaune',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#d50000',
    },
    {
      name: 'Toulouse FC',
      shortName: 'Toulouse',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/63/Toulouse_FC_2018_logo.svg',
      stadium: 'Stadium de Toulouse',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#695089',
    },
    {
      name: 'Saint-Étienne',
      shortName: 'St. Étienne',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/25/AS_Saint-%C3%89tienne_logo.svg',
      stadium: 'Stade Geoffroy-Guichard',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#009e60',
    },
    {
      name: 'RC Strasbourg',
      shortName: 'Strasbourg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/80/Racing_Club_de_Strasbourg_logo.svg',
      stadium: 'Stade de la Meinau',
      country: CountryEnum.FRANCE,
      teamPrimaryColor: '#00a0e4',
    },
  ],
  [LeagueEnum.EREDIVISIE]: [
    {
      name: 'Ajax',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
      stadium: 'Johan Cruyff Arena',
      country: CountryEnum.NETHERLANDS,
      teamPrimaryColor: '#d3122e',
    },
    {
      name: 'PSV Eindhoven',
      shortName: 'PSV',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg',
      stadium: 'Philips Stadion',
      country: CountryEnum.NETHERLANDS,
      teamPrimaryColor: '#ec1b24',
    },
    {
      name: 'Feyenoord',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Feyenoord_logo_since_2009.svg',
      stadium: 'De Kuip',
      country: CountryEnum.NETHERLANDS,
      teamPrimaryColor: '#ff1710',
    },
    {
      name: 'FC Twente',
      shortName: 'Twente',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e3/FC_Twente.svg',
      stadium: 'De Grolsch Veste',
      country: CountryEnum.NETHERLANDS,
      teamPrimaryColor: '#e70011',
    },
  ],
  [LeagueEnum.PRIMEIRA_LIGA]: [
    {
      name: 'Porto',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg',
      stadium: 'Estádio do Dragão',
      country: CountryEnum.PORTUGAL,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Benfica',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg',
      stadium: 'Estádio da Luz',
      country: CountryEnum.PORTUGAL,
      teamPrimaryColor: '#ff0000',
    },
    {
      name: 'Sporting CP',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Sporting_Clube_de_Portugal_%28Logo%29.svg',
      stadium: 'Estádio José Alvalade',
      country: CountryEnum.PORTUGAL,
      teamPrimaryColor: '#078156',
    },
    {
      name: 'SC Braga',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/S.C._Braga_logo.svg',
      stadium: 'Estádio Municipal de Braga',
      country: CountryEnum.PORTUGAL,
      teamPrimaryColor: '#c9261c',
    },
  ],
  [LeagueEnum.SUPERETTAN]: [
    {
      name: 'IK Oddevold',
      shortName: 'Oddevold',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6160.png',
      stadium: 'Rimnersvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#004a97',
      id: '6160',
    },
    {
      name: 'Falkenbergs FF',
      shortName: 'Falkenberg',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6545.png',
      stadium: 'Falcon Alkoholfri Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#f2a900',
      id: '6545',
    },
    {
      name: 'Västerås SK',
      shortName: 'Västerås',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6161.png',
      stadium: 'Hitachi Energy Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#005b3d',
      id: '6194',
    },
    {
      name: 'Östersunds FK',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/2004.png',
      stadium: 'Jämtkraft Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#f2a900',
      id: '2004',
    },
    {
      name: 'Landskrona BoIS',
      shortName: 'Landskrona',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8511.png',
      stadium: 'Landskrona IP',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#000',
      id: '8511',
    },
    {
      name: 'Kalmar FF',
      shortName: 'Kalmar',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9892.png',
      stadium: 'Guldfågeln Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#da2127',
      id: '9892',
    },
    {
      name: 'Varbergs BoIS',
      shortName: 'Varberg',
      id: '6692',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6692.png',
      stadium: 'Påskbergsvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#259548',
    },
    {
      name: 'Örgryte IS',
      shortName: 'ÖIS',
      id: '10002',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10002.png',
      stadium: 'Gamla Ullevi',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#981b2e',
    },
    {
      name: 'Sandvikens IF',
      shortName: 'Sandviken',
      id: '6241',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6241.png',
      stadium: 'Jernvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '##ab1614',
    },
    {
      name: 'GIF Sundsvall',
      shortName: 'Sundsvall',
      id: '8359',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8359.png',
      stadium: 'NP3 Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Trelleborgs FF',
      shortName: 'Trelleborg',
      id: '8333',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8333.png',
      stadium: 'Vångavallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#1d6aaf',
    },
    {
      name: 'IK Brage',
      shortName: 'Borlänge Energi Arena',
      id: '6690',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/6690.png',
      stadium: 'Bragvallen',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#007736',
    },
    {
      name: 'Umeå FC',
      shortName: 'Umeå',
      id: '8601',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8601.png',
      stadium: 'Umeå Energi Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#00529f',
    },
    {
      name: 'Helsingborgs IF',
      shortName: 'Helsingborg',
      id: '9859',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9859.png',
      stadium: 'Olympia',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#e00316',
    },
    {
      name: 'Örebro SK',
      shortName: 'Örebro',
      id: '8527',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8527.png',
      stadium: 'Behrn Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'Utsiktens BK',
      shortName: 'Utsikten',
      id: '73158',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/73158.png',
      stadium: 'Bravida Arena',
      country: CountryEnum.SWEDEN,
      teamPrimaryColor: '#0977c1',
    },
  ],
  [LeagueEnum.ELITESERIEN]: [
    {
      name: 'Bodø/Glimt',
      id: '8402',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8402.png',
      stadium: 'Aspmyra Stadion',
      country: CountryEnum.NORWAY,
      teamPrimaryColor: '#fcde11',
    },
    {
      name: 'Rosenborg',
      id: '8422',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8422.png',
      stadium: 'Lerkendal Stadion',
      country: CountryEnum.NORWAY,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'Viking FK',
      id: '8478',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8478.png',
      stadium: 'SR-Bank Arena',
      country: CountryEnum.NORWAY,
      teamPrimaryColor: '#72121c',
    },
    {
      name: 'Molde FK',
      id: '9917',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9917.png',
      stadium: 'Aker Stadion',
      country: CountryEnum.NORWAY,
      teamPrimaryColor: '#0364af',
    },
  ],
  [LeagueEnum.SUPERLIGA]: [
    {
      name: 'FC København',
      shortName: 'København',
      id: '8391',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8391.png',
      stadium: 'Parken',
      country: CountryEnum.DENMARK,
      teamPrimaryColor: '#00189b',
    },
    {
      name: 'Brøndby IF',
      shortName: 'Brøndby',
      id: '8595',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8595.png',
      stadium: 'Brøndby Stadion',
      country: CountryEnum.DENMARK,
      teamPrimaryColor: '#f6c600',
    },
    {
      name: 'FC Midtjylland',
      shortName: 'Midtjylland',
      id: '8113',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8113.png',
      stadium: 'MCH Arena',
      country: CountryEnum.DENMARK,
      teamPrimaryColor: '#be0e0c',
    },
    {
      name: 'Nordsjælland',
      id: '10202',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10202.png',
      stadium: 'Right to Dream Park',
      country: CountryEnum.DENMARK,
      teamPrimaryColor: '#fd2824',
    },
  ],
  [LeagueEnum.TURKISH_SUPER_LIG]: [
    {
      name: 'Galatasaray',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8637.png',
      stadium: 'Türk Telekom Stadium',
      country: CountryEnum.TURKEY,
      teamPrimaryColor: '#ffb317',
      id: '8637',
    },
    {
      name: 'Fenerbahçe',
      fotMobName: 'Fenerbahce',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8695.png',
      stadium: 'Şükrü Saracoğlu Stadium',
      country: CountryEnum.TURKEY,
      teamPrimaryColor: '#083475',
      id: '8695',
    },
    {
      name: 'Beşiktaş',
      fotMobName: 'Besiktas',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10188.png',
      stadium: 'Vodafone Park',
      country: CountryEnum.TURKEY,
      teamPrimaryColor: '#080808',
      id: '10188',
    },
  ],
  [LeagueEnum.GREEK_SUPER_LEAGUE]: [
    {
      name: 'Olympiakos',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8638.png',
      stadium: 'Georgios Karaiskakis Stadium',
      country: CountryEnum.GREECE,
      teamPrimaryColor: '#ed1b24',
    },
    {
      name: 'PAOK',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8619.png',
      stadium: 'Toumba Stadium',
      country: CountryEnum.GREECE,
      teamPrimaryColor: '#040404',
    },
    {
      name: 'AEK Athens',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/8563.png',
      stadium: 'Olympic Stadium',
      country: CountryEnum.GREECE,
      teamPrimaryColor: '#ffd300',
    },
    {
      name: 'Panathinaikos',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10200.png',
      stadium: 'Olympic Stadium',
      country: CountryEnum.GREECE,
      teamPrimaryColor: '#00793e',
    },
  ],
  [LeagueEnum.BELGIAN_PRO_LEAGUE]: [
    {
      name: 'Club Brugge',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d0/Club_Brugge_KV_logo.svg',
      stadium: 'Jan Breydel Stadium',
      country: CountryEnum.BELGIUM,
      teamPrimaryColor: '#0d5eaf',
    },
  ],
  [LeagueEnum.UKRAINIAN_PREMIER_LEAGUE]: [
    {
      name: 'Shakhtar Donetsk',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a1/FC_Shakhtar_Donetsk.svg',
      stadium: 'Volksparkstadion',
      country: CountryEnum.UKRAINE,
      teamPrimaryColor: '#ed6a01',
    },
  ],
  [LeagueEnum.SCOTTISH_PREMIERSHIP]: [
    {
      name: 'Celtic',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/71/Celtic_FC_crest.svg',
      stadium: 'Celtic Park',
      country: CountryEnum.SCOTLAND,
      teamPrimaryColor: '#008848',
    },
  ],
  [LeagueEnum.AUSTRIAN_BUNDESLIGA]: [
    {
      name: 'Red Bull Salzburg',
      shortName: 'RB Salzburg',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/77/FC_Red_Bull_Salzburg_logo.svg',
      stadium: 'Red Bull Arena',
      country: CountryEnum.AUSTRIA,
      teamPrimaryColor: '#d50000',
    },
    {
      name: 'Sturm Graz',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/91/SK_Sturm_Graz_logo.svg',
      stadium: 'Merkur Arena',
      country: CountryEnum.AUSTRIA,
      teamPrimaryColor: '#000000',
    },
    {
      name: 'Rapid Wien',
      id: '10015',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10015.png',
      stadium: 'Allianz Stadion',
      country: CountryEnum.AUSTRIA,
      teamPrimaryColor: '#007a33',
    },
    {
      name: 'FK Austria Wien',
      shortName: 'Austria Wien',
      id: '10011',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/10011.png',
      stadium: 'Generali Arena',
      country: CountryEnum.AUSTRIA,
      teamPrimaryColor: '#451679',
    },
  ],
  [LeagueEnum.SWISS_SUPER_LEAGUE]: [
    {
      name: 'Young Boys',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6b/BSC_Young_Boys_logo.svg',
      stadium: 'Wankdorf Stadium',
      country: CountryEnum.SWITZERLAND,
      teamPrimaryColor: '#f9cc0f',
    },
    {
      name: 'FC Basel',
      id: '9913',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/9913.png',
      stadium: 'St. Jakob-Park',
      country: CountryEnum.SWITZERLAND,
      teamPrimaryColor: '#e50000',
    },
  ],
  [LeagueEnum.CZECH_FIRST_LEAGUE]: [
    {
      name: 'Sparta Prag',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/AC-Sparta-LOGO2021.svg',
      stadium: 'epet ARENA',
      country: CountryEnum.CZECH_REPUBLIC,
      teamPrimaryColor: '#b8282e',
    },
    {
      name: 'Slavia Prag',
      id: '7787',
      logoUrl: 'https://images.fotmob.com/image_resources/logo/teamlogo/7787.png',
      stadium: 'Sinobo Stadium',
      country: CountryEnum.CZECH_REPUBLIC,
      teamPrimaryColor: '##d92232',
    },
  ],
  [LeagueEnum.CROATIAN_FIRST_FOOTBALL_LEAGUE]: [
    {
      name: 'Dinamo Zagreb',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Dinamo_Zagreb_logo.png',
      stadium: 'Stadion Maksimir',
      country: CountryEnum.CROATIA,
      teamPrimaryColor: '#0047ab',
    },
  ],
  [LeagueEnum.SLOVAK_1_LIGA]: [
    {
      name: 'Slovan Bratislava',
      shortName: 'S. Bratislava',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/01/SK_Slovan_Bratislava_logo.svg',
      stadium: 'Tehelné pole',
      country: CountryEnum.SLOVAKIA,
      teamPrimaryColor: '#2db1e7',
    },
  ],
  [LeagueEnum.SERBIAN_SUPER_LIGA]: [
    {
      name: 'Crvena Zvezda',
      shortName: 'Red Star',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/15/FK_Crvena_Zvezda_Logo.svg',
      stadium: 'Rajko Mitić Stadium',
      country: CountryEnum.SERBIA,
      teamPrimaryColor: '#d50000',
    },
  ],
  [LeagueEnum.AZERBAIJAN_PREMIER_LEAGUE]: [
    {
      name: 'Qarabağ',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Qaraba%C4%9F_FK_logo.png',
      stadium: 'Azersun Arena',
      country: CountryEnum.AZERBAIJAN,
      teamPrimaryColor: '#1b1059',
    },
  ],
  [LeagueEnum.NATIONS]: nationalTeams,
  [LeagueEnum.PLACEHOLDER]: [
    {
      name: 'Placeholder A',
      logoUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAMAAAAM7l6QAAAAaVBMVEUAAACWmo+YnJSOkoqgo52sr6m6vbYwMy4BAwAXGhWfopuEiIIEBgMgIh5NUEoMEAkBAwA+QT2rr6eDh4AEBQQEBwIcHxg9QDkSFA9XWlRzd3AoKycAAAADBQNna2QNEAsCBQBKTkYYGxYxc3abAAAAI3RSTlMAIyMjIx4ePyo5HioGPjkyHjkjIxcRRT4+Mio5IwsyKiMyMqsVmQMAAAEdSURBVCjPddLbtoIgFEBR2BcQSERN07LLOf//kVGpRNZ6Y0w2OFSRt9/n6xyHQ23CdztPRh+ZXV0WXS67LlxN6VslAUDBqM017M+LVqX2o7MWXhEzXnytq3m25BiBlHFYPkKwrFS5e/GJABEfthbXdFo4QlZcI5CZ7x6wTRvSloWNQ7llXLg6Wrl1V81cXBjlZ81x4ev4he3KwX9hNU4zd5olQizjev14p2bLFF9aenSC1FOdEUuhZoS3ULbK38Ra2WA+jVafExd/Ft5qQF3+RWqnG0mQ7if1HE7jnuORq/JYiKzBASamXuR1vZLr4arf/M/hoFASIUDLh3R0ul4zSRldJc29sW1Lafaj0DtWrp/Ej7qh9kMnfjfd8vUdUWkNqdfapjEAAAAASUVORK5CYII=',
      stadium: 'Stadium',
      country: CountryEnum.PLACEHOLDER,
      isPlaceholder: true,
      teamPrimaryColor: '#e9e9e9',
    },
    {
      name: 'Placeholder B',
      logoUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAMAAAAM7l6QAAAAaVBMVEUAAACWmo+YnJSOkoqgo52sr6m6vbYwMy4BAwAXGhWfopuEiIIEBgMgIh5NUEoMEAkBAwA+QT2rr6eDh4AEBQQEBwIcHxg9QDkSFA9XWlRzd3AoKycAAAADBQNna2QNEAsCBQBKTkYYGxYxc3abAAAAI3RSTlMAIyMjIx4ePyo5HioGPjkyHjkjIxcRRT4+Mio5IwsyKiMyMqsVmQMAAAEdSURBVCjPddLbtoIgFEBR2BcQSERN07LLOf//kVGpRNZ6Y0w2OFSRt9/n6xyHQ23CdztPRh+ZXV0WXS67LlxN6VslAUDBqM017M+LVqX2o7MWXhEzXnytq3m25BiBlHFYPkKwrFS5e/GJABEfthbXdFo4QlZcI5CZ7x6wTRvSloWNQ7llXLg6Wrl1V81cXBjlZ81x4ev4he3KwX9hNU4zd5olQizjev14p2bLFF9aenSC1FOdEUuhZoS3ULbK38Ra2WA+jVafExd/Ft5qQF3+RWqnG0mQ7if1HE7jnuORq/JYiKzBASamXuR1vZLr4arf/M/hoFASIUDLh3R0ul4zSRldJc29sW1Lafaj0DtWrp/Ej7qh9kMnfjfd8vUdUWkNqdfapjEAAAAASUVORK5CYII=',
      stadium: 'Stadium',
      country: CountryEnum.PLACEHOLDER,
      isPlaceholder: true,
      teamPrimaryColor: '#f9f9f9',
    },
  ],
};
